Adding Admin Controller, documentation, initial Git integration
Azure/azure-sdk-tools pull request #1571
Opened 2021-04-22 22:53 UTC by scbedd

2021-04-22 22:56 UTC, scbedd commented on tools/test-proxy/Azure.Sdk.Tools.TestProxy/Properties/launchSettings.json
> +      "commandLineArgs": "--storage-location \"C:/repo/scraps/test-proxy/repo\"",
Will clean this up, then add to gitignore.

2021-04-22 23:23 UTC, mikeharder commented on tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs
> +            }
```suggestion
            if (Request.Headers.TryGetValue("x-recording-sha", out var sha))
            {
                _recordingHandler.Checkout(sha);
            }
```

2021-04-23 00:01 UTC, mikeharder requested changes

2021-04-23 00:02 UTC, mikeharder approved these changes

2021-04-23 01:30 UTC, merged