[Perf] Use Java Version Tooling to Configure Version Changes in Perf Tooling
Azure/azure-sdk-tools pull request #3516
Opened 2022-06-28 21:47 UTC by alzimmermsft

Updates the Java Perf framework to use the standard version tooling found in `azure-sdk-for-java`.

2022-09-01 16:05 UTC, alzimmermsft commented
Example of this in action: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1821644&view=results

2022-09-02 01:25 UTC, mikeharder commented
/azp run tools - perf-automation - tests

2022-09-02 01:42 UTC, mikeharder requested changes
I'm just starting to look at this, but I'm concerned this might have broken the "package versions" run.  Before this PR, for the "package versions" run we saw:

```
[07:10:16.943] [INFO] Reactor Build Order:
[07:10:16.943] [INFO] 
[07:10:16.944] [INFO] Microsoft Azure SDK for Java Parent                                [pom]
[07:10:16.944] [INFO] Maven Build Tools                                                  [jar]
[07:10:16.944] [INFO] Microsoft Azure SDK for Java - Client Libraries                    [pom]
[07:10:16.944] [INFO] Microsoft Azure SDK for Java - Performance Test Libraries Parent   [pom]
[07:10:16.944] [INFO] Microsoft Azure Java Performance Test Library                      [jar]
[07:10:16.945] [INFO] azure-storage-perf                                                 [jar]
```

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1823347&view=logs&j=dc42670d-1473-57cd-faea-36a5bc05eab2&t=dfb494f3-2da1-55d1-b8fd-9d227ffe033a&l=292

After this PR:

```
[01:28:25.502] [INFO] Reactor Build Order:
[01:28:25.502] [INFO] 
[01:28:25.502] [INFO] Microsoft Azure SDK for Java Parent                                [pom]
[01:28:25.502] [INFO] Maven Build Tools                                                  [jar]
[01:28:25.502] [INFO] Microsoft Azure SDK for Java - Client Libraries                    [pom]
[01:28:25.502] [INFO] Microsoft Azure Java Core Library                                  [jar]
[01:28:25.502] [INFO] Microsoft Azure Java Core Test Library                             [jar]
[01:28:25.502] [INFO] Microsoft Azure Netty HTTP Client Library                          [jar]
[01:28:25.502] [INFO] Microsoft Azure OkHttp HTTP Client Library                         [jar]
[01:28:25.502] [INFO] Microsoft Azure SDK for Java - Performance Test Libraries Parent   [pom]
[01:28:25.502] [INFO] Microsoft Azure Java Performance Test Library                      [jar]
[01:28:25.502] [INFO] Microsoft Azure common module for Storage                          [jar]
[01:28:25.502] [INFO] Microsoft Azure internal Avro module for Storage                   [jar]
[01:28:25.502] [INFO] Microsoft Azure client library for Blob Storage                    [jar]
[01:28:25.502] [INFO] Microsoft Azure client library for Blob Storage cryptography       [jar]
[01:28:25.502] [INFO] Microsoft Azure client library for File Share Storage              [jar]
[01:28:25.502] [INFO] Microsoft Azure client library for File Storage Data Lake          [jar]
[01:28:25.502] [INFO] azure-storage-perf                                                 [jar]
```

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1825915&view=logs&j=dc42670d-1473-57cd-faea-36a5bc05eab2&t=dfb494f3-2da1-55d1-b8fd-9d227ffe033a&l=81

I will move https://github.com/Azure/azure-sdk-tools/pull/3716 (Print runtime package versions) to the top of my backlog, and see if I can get this implemented for Java and merged tomorrow.  Then we can verify the Java runtime package versions before/after this PR more easily, without relying on the build logs.

2022-09-07 18:00 UTC, mikeharder commented
/azp run tools - perf-automation - tests

2022-09-07 20:36 UTC, mikeharder approved these changes
Approved pending formatting changes

2022-09-07 20:36 UTC, mikeharder commented on tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Java.cs
> +                if (trimmedLine.StartsWith('#') || trimmedLine.StartsWith("beta_") || trimmedLine.StartsWith("unreleased_")) continue;
```suggestion
                if (string.IsNullOrEmpty(trimmedLine) ||
                    trimmedLine.StartsWith('#') ||
                    trimmedLine.StartsWith("beta_", StringComparison.Ordinal) ||
                    trimmedLine.StartsWith("unreleased_", StringComparison.Ordinal))
                {
                    continue;
                }
```

2022-09-07 20:36 UTC, mikeharder commented on tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Java.cs
> +                    if (!sourceVersions.TryGetValue(v.Key, out packageVersion)) continue;
```suggestion
                    if (!sourceVersions.TryGetValue(v.Key, out packageVersion))
                    {
                        continue;
                    }
```

2022-09-07 20:37 UTC, mikeharder commented on tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Java.cs
> +                if (trimmedLine.StartsWith('#') || trimmedLine.StartsWith("beta_") || trimmedLine.StartsWith("unreleased_")) continue;
Or you could use `StringComparison.OrdinalIgnoreCase` if you want to match any case.

2022-09-07 20:52 UTC, merged