Update cadl to typeSpec
Azure/azure-sdk-tools pull request #5708
Opened 2023-03-14 23:31 UTC by chidozieononiwu

CADL to TypeSpec rename. Should resolve https://github.com/Azure/azure-sdk-tools/issues/5635

Blocked by:
Updates to https://github.com/Azure/azure-sdk-tools/blob/7c10ce5ef4641263b81e775aa181d82750a83da1/src/dotnet/APIView/APIViewWeb/Languages/CadlLanguageService.cs
Updated to DataBase

2023-03-14 23:38 UTC, tjprescott requested changes
I see all the updates from Cadl to TypeSpec, but if someone selects "TypeSpec" the filters should still include any existing APIViews that have a language of type "Cadl"

2023-03-14 23:40 UTC, chidozieononiwu commented
> I see all the updates from Cadl to TypeSpec, but if someone selects "TypeSpec" the filters should still include any existing APIViews that have a language of type "Cadl"

For that I plan to run a script to update all cadl values in the database. That will happen before this change is deployed.

2023-03-20 23:29 UTC, chidozieononiwu commented
Do we want to have only `TypeSpec` or `TypeSpec | Cadl` on the UI side to accomodate teams that are not yet converting to TypeSpec @weshaggard @tjprescott

2023-03-21 15:41 UTC, tjprescott commented
My strong recommendation would be to support `Cadl` as an alias of `TypeSpec`. For example, only choose `TypeSpec` in the filter, but it should show APIViews that are marked as langauge `TypeSpec` or `Cadl`. While a one-time conversion will "fix" any Cadl views currently in the system, if another gets uploaded it will just be silently swallowed by the void.

2023-03-21 22:18 UTC, weshaggard commented
If using an alias (i.e. when querying the DB you can query for both TypeSpec and Cadl) is easy enough I think that is reasonable. I wouldn't display Cadl in the UI any longer.

2023-03-21 22:32 UTC, chidozieononiwu commented
> If using an alias (i.e. when querying the DB you can query for both TypeSpec and Cadl) is easy enough I think that is reasonable. I wouldn't display Cadl in the UI any longer.

I have gone with this approach.

2023-03-22 18:34 UTC, maririos commented on src/dotnet/APIView/APIViewWeb/Helpers/LanguageServiceHelpers.cs
> +        public static string[] SupportedLanguages = new string[] { "C", "C++", "C#", "TypeSpec", "Go", "Java", "JavaScript", "Json", "Kotlin", "Python", "Swagger", "Swift", "Xml" };
nit: order of `TypeSpec`

2023-03-22 18:36 UTC, maririos approved these changes

2023-03-22 20:49 UTC, merged