[Update RecordMatcher.cs
Azure/azure-sdk-tools pull request #6152
Opened 2023-05-11 21:31 UTC by HarshaNalluru

Ignoring the "Accept-Language" header

@timovv shared the discomfort about the number of times he had to re-record because his locale is en-CA instead of en-US.

And @jeremymeng 's puppeteer upgrade may unveil a pain later on, example below
```
RecorderError: Unable to find a record for the request POST https://keyvault_name.vault.azure.net/keys/listKeyName-cangettheversionsofakeypaged-/create?api-version=7.4 Header differences: <sec-ch-ua> values differ, request <"HeadlessChrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24">, record <> <Accept-Language> is absent in request, value <en-US> Body differences:
```

`sec-ch-ua` is just fixed in #6151

2023-05-11 21:37 UTC, scbedd approved these changes
👍 

Going to talk to Mike about this one.

2023-05-11 21:50 UTC, HarshaNalluru commented
Upon discussing more with @scbedd.. 

The issue posted above won't be fixed by adding to the ignore headers, we'll have to exclude it since ignore would mean that, we'll check for its presence.

And excluding feels wrong as there might be real utility.

cc @jeremymeng

2023-05-15 21:04 UTC, scbedd reviewed
Rescinding approval till I chat with Mike.

2023-05-15 21:05 UTC, scbedd requested changes
Holding off.

2023-07-28 08:31 UTC, closed without merging