Fix analyzer issues
Azure/azure-sdk-tools pull request #7222
Opened 2023-11-01 10:14 UTC by pshao25

Fix https://github.com/Azure/autorest.csharp/issues/3710
Fix https://github.com/Azure/autorest.csharp/issues/3708

2023-11-01 14:33 UTC, jsquire requested changes
Can we please add details to the description.   What are the intended changes to the current ruleset?  The code itself has few comments as to the intent of the rule and what pattern its intending to validate.

2023-11-02 02:33 UTC, pshao25 commented
> Can we please add details to the description. What are the intended changes to the current ruleset? The code itself has few comments as to the intent of the rule and what pattern its intending to validate.

Updated.

2023-11-06 09:45 UTC, pshao25 commented
@m-nash could you help review? This blocks we change constructors behaviors as we discussed in https://github.com/Azure/autorest.csharp/issues/3706#issuecomment-1752374728

2023-11-10 15:50 UTC, AlexanderSher commented on src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers.Tests/AZC0002Tests.cs
> +namespace RandomNamespace
Can we add cases with `RandomNamespace.Azure` and `Azure.RandomNamespace`?

2023-11-13 06:10 UTC, pshao25 commented on src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientMethodsAnalyzer.cs
> +                if (!IsOrImplements(pageableReturn, BinaryDataTypeName, SystemNamespace))
If `My.System.BinaryData` extends `System.BinaryData` then it's still `true` else `false`.

2023-11-14 13:20 UTC, AlexanderSher commented on src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientMethodsAnalyzer.cs
> +                if (!IsOrImplements(pageableReturn, BinaryDataTypeName, SystemNamespace))
Can you please add a test for it?

2023-11-16 14:15 UTC, AlexanderSher approved these changes

2023-11-16 21:49 UTC, merged