Fix Bug in Conversation Page
Azure/azure-sdk-tools pull request #7527
Opened 2024-01-13 03:04 UTC by chidozieononiwu

- Resolve bug in Conversation Page for Reviews with SampleRevision comments

2024-01-16 14:21 UTC, praveenkuttappan requested changes

2024-01-16 14:21 UTC, praveenkuttappan commented on src/dotnet/APIView/APIViewWeb/Startup.cs
> +            //services.AddHostedService<ReviewBackgroundHostedService>();
Assuming this was unintentional. Can you please uncomment them?

2024-01-17 00:34 UTC, maririos commented
> Resolve bug in Conversation Page for Reviews with SampleRevision comments

Could you expand on what the bug is and the fix? looking at the code I didn't fully understand

2024-01-17 00:51 UTC, chidozieononiwu commented
> > Resolve bug in Conversation Page for Reviews with SampleRevision comments
> 
> Could you expand on what the bug is and the fix? looking at the code I didn't fully understand

Its probing to find the correct line in the SamplesRevisions where the comment was made. The bug comes from the fact that revisions used to be ordered in reverse.

> > Resolve bug in Conversation Page for Reviews with SampleRevision comments
> 
> Could you expand on what the bug is and the fix? looking at the code I didn't fully understand

Its probing for the line in the `SamplesRevision` that has the comment. Since the SamplesRevisions are ordered in reverse for the loop the lookup should also be from the end of the list inorder to reference the correct SamplesRevision.

2024-01-17 01:13 UTC, maririos approved these changes

2024-01-19 13:35 UTC, maririos approved these changes

2024-01-19 18:40 UTC, merged