Add ContentType header to Update-GitHubIssue
Azure/azure-sdk-tools pull request #7630
Opened 2024-02-05 02:46 UTC by Alancere

<img width="457" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/46921893/f066d1ca-cf78-4501-89f5-9cb1ddab3a4b">

2024-02-05 02:52 UTC, azure-sdk commented
The following pipelines have been queued for testing:<br>[java - template](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3467691)<br>[java - template - tests](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3467692)<br>[js - template](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3467693)<br>[net - template](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3467694)<br>[net - template - tests](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3467695)<br>[python - template](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3467696)<br>[python - template - tests](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3467697) <br>You can sign off on the approval gate to test the release stage of each pipeline. <br>See [eng/common workflow](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/README.md#workflow)

2024-02-05 06:37 UTC, raych1 commented on eng/common/scripts/Invoke-GitHubAPI.ps1
> +          -ContentType "application/x-www-form-urlencoded"
Can we use `application/json` as the body is converted to JSON in line#402?

2024-02-05 07:08 UTC, azure-sdk commented
The following pipelines have been queued for testing:<br>[java - template](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3467897)<br>[java - template - tests](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3467898)<br>[js - template](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3467899)<br>[net - template](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3467900)<br>[net - template - tests](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3467901)<br>[python - template](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3467902)<br>[python - template - tests](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3467903) <br>You can sign off on the approval gate to test the release stage of each pipeline. <br>See [eng/common workflow](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/README.md#workflow)

2024-02-05 22:39 UTC, weshaggard approved these changes

2024-02-06 00:24 UTC, danieljurek requested changes
The current syntax will not pick up the `-ContentType` parameter because the script does not have a backtick to continue parsing to the next line.

2024-02-06 00:52 UTC, weshaggard commented
@raych1 Lets please be sure to test this change.

2024-02-06 00:55 UTC, danieljurek approved these changes

2024-02-06 00:56 UTC, azure-sdk commented
The following pipelines have been queued for testing:<br>[java - template](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3470823)<br>[java - template - tests](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3470824)<br>[js - template](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3470825)<br>[net - template](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3470826)<br>[net - template - tests](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3470827)<br>[python - template](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3470828)<br>[python - template - tests](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_build/results?buildId=3470829) <br>You can sign off on the approval gate to test the release stage of each pipeline. <br>See [eng/common workflow](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/README.md#workflow)

2024-02-06 07:48 UTC, raych1 commented
> @raych1 Lets please be sure to test this change.

@weshaggard , this is the [test pipeline run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3471789&view=logs&j=33796ffc-d0c5-548c-0c1d-9d1ddb84594a&t=49452e74-a04a-59c1-118d-9b0749e7229c)

2024-02-06 08:51 UTC, merged

2024-02-06 16:55 UTC, weshaggard commented
@raych1 I don't suspect that is hitting this code path on PS7.4. Just please be sure to check the same pipeline that was failing in the go repo with this fix.

2024-02-19 03:25 UTC, raych1 commented
> @raych1 I don't suspect that is hitting this code path on PS7.4. Just please be sure to check the same pipeline that was failing in the go repo with this fix.

@weshaggard , the failure was caught in the Go release pipeline, and we will verify it during this month's release.