Fix AZC0006 and AZC0007 to accept endpoint as an exception
Azure/azure-sdk-tools pull request #8478
Opened 2024-06-20 08:50 UTC by pshao25

2024-06-20 13:35 UTC, jsquire requested changes
Reading Ted's comment on the linked issue, I do not think the above is correct.    What I believe Ted stated is that, by default, we want to limit constructors to the pattern:

```csharp
public SomeType(Uri endpoint, AClientOptions options);
```

If we have a constructor pattern like the above, it would be a special case that the architects allowed to deviate from our standard patterns and, thus, would require suppressing the analyzer.

@tg-msft, @KrzysztofCwalina:  Can you offer thoughts, please?

2024-06-20 16:25 UTC, KrzysztofCwalina commented
I agree with that @jsquire said. Moreover, if we do allow an additional required parameter (per architect review), the parameter would have to always be in the same location in the signature, not like in the description of the PR, i.e. the signatures would have to be:

```
public AClient(string required): this(new Uri("http://localhost:3000/"), required, new AClientOptions()){}
public AClient(string required, Uri endpoint, AClientOptions options){}
```

2024-06-21 02:30 UTC, pshao25 commented
@jsquire @KrzysztofCwalina So to confirm the optional endpoint cases:
1. if there is no required parameter, constructors should be
```C#
public AClient(): this(new Uri("http://localhost:3000/"), new AClientOptions()){}
public AClient(Uri endpoint, AClientOptions options){}
```
2. if there is required parameter, constructors should be
```C#
public AClient(string required): this(required, new Uri("http://localhost:3000/"),new AClientOptions()){}
public AClient(string required, Uri endpoint, AClientOptions options){}
```

And both of these "optional endpoint" cases should fail the analyzer to let customers suppress themselves.

@KrzysztofCwalina @tg-msft please confirm especially case 2 because our generator is not going this way now.

2024-06-21 13:34 UTC, jsquire commented
@pshao25:  For this statement:

> And both of these "optional endpoint" cases should fail the analyzer to let customers suppress themselves.

Who are "customers?"   The Azure SDK analyzers run only in the Azure SDK repositories.   So, the rule enforcement is intentionally scoped to Azure conventions.   If a customer is using TypeSpec and our C# generator for TypeSpec to create a non-Azure library, they are doing so in their own repository - which does not have these analyzers.

The root question that we need to answer here is "will Azure libraries in our repository every deviate from this rule without an architect exception?"

2024-08-30 08:34 UTC, closed without merging