[tsp-client] Update rest-api-diff dependency
Azure/azure-sdk-tools pull request #8840
Opened 2024-08-14 19:42 UTC by tjprescott

2024-08-14 19:50 UTC, mikeharder approved these changes

2024-08-14 19:59 UTC, mikeharder requested changes
Remove comma

2024-08-14 19:59 UTC, mikeharder commented on tools/tsp-client/package.json
> +    "@azure-tools/rest-api-diff": ">=0.1.0, <1.0.0",
```suggestion
    "@azure-tools/rest-api-diff": ">=0.1.0 <1.0.0",
```

2024-08-14 20:45 UTC, mikeharder approved these changes

2024-08-16 22:44 UTC, catalinaperalta approved these changes

2024-08-20 17:09 UTC, tjprescott commented
/checkenforcer evaluate

2024-08-20 17:09 UTC, tjprescott commented
/check-enforcer evaluate

2024-08-20 17:10 UTC, merged