Allow uploads of dll files
Azure/azure-sdk-tools pull request #8903
Opened 2024-08-29 00:43 UTC by chidozieononiwu

- Allow upload of dll files for C#

2024-08-29 17:07 UTC, praveenkuttappan requested changes
As discussed, let's fix the label to correctly convey the message.

2024-08-29 19:01 UTC, chidozieononiwu commented
> As discussed, let's fix the label to correctly convey the message.

I have updated it.

2024-08-29 20:12 UTC, maririos commented on src/dotnet/APIView/ClientSPA/src/app/_components/revisions-list/revisions-list.component.ts
> +        this.acceptedFilesLabelForReviewUpload = ".nupkg or .dll";
could you add a screen that shows how this is displayed in the overall message?

2024-09-04 16:46 UTC, maririos commented
Thanks! looking at the image, I have 2 suggestions:
- Update the # 2 instructions to "Upload the resulting .nupkg or dll file"
- Update the message on the button to "Upload file" or "Select file"

2024-09-09 16:19 UTC, praveenkuttappan approved these changes

2024-09-09 17:06 UTC, merged