Expose fullyCompatible parameter of converter
Azure/azure-sdk-tools pull request #9238
Opened 2024-10-23 13:12 UTC by pshao25

2024-10-24 05:34 UTC, tadelesh approved these changes

2024-10-24 16:50 UTC, catalinaperalta requested changes
Can you please also go into more detail about the flag in the readme under the section for the `convert` command. Otherwise folks may not know what a "fully compatible typespec" is

2024-10-24 16:50 UTC, catalinaperalta commented on tools/tsp-client/src/commands.ts
> +  const fullyCompatible = argv["fullyCompatible"];
This needs to be using kebab case like all the other flags
```suggestion
  const fullyCompatible = argv["fully-compatible"];
```

2024-10-24 16:50 UTC, catalinaperalta commented on tools/tsp-client/src/index.ts
> +        .option("fullyCompatible", {
```suggestion
        .option("fully-compatible", {
```

2024-10-25 08:13 UTC, pshao25 commented
> Can you please also go into more detail about the flag in the readme under the section for the `convert` command. Otherwise folks may not know what a "fully compatible typespec" is

Updated. I actually planned to update this to TypeSpec-Azure document.

2024-10-25 22:39 UTC, catalinaperalta approved these changes
Thanks for the fixes!

2024-10-25 22:39 UTC, catalinaperalta commented on tools/tsp-client/CHANGELOG.md
> +- Expose `fullyCompatible` argument for `@autorest/openapi-to-typespec`
Nit: 
```suggestion
- Expose `fully-compatible` argument for `@autorest/openapi-to-typespec`
```

2024-10-25 22:39 UTC, catalinaperalta commented on tools/tsp-client/README.md
> +Convert an existing swagger specification to a TypeSpec project. This command should only be run once to get started working on a TypeSpec project. TypeSpec projects will need to be optimized manuall
Nit: 
```suggestion
Convert an existing swagger specification to a TypeSpec project. This command should only be run once to get started working on a TypeSpec project. TypeSpec projects will need to be optimized manually and fully reviewed after conversion. When using this command a path or url to a swagger README file is required through the `--swagger-readme` flag. By default, the converted TypeSpec project will leverage TypeSpec built-in libraries with standard patterns and templates (highly recommended), which will cause discrepancies between the generated TypeSpec and original swagger. If you really don't want this intended discrepancy, add `--fully-compatible` flag to generate a TypeSpec project that is fully compatible with the swagger.
```

2024-10-31 05:23 UTC, pshao25 commented
/check-enforcer override

2024-10-31 05:24 UTC, merged